/* eslint-disable prettier/prettier */
'use client';

import type { Metadata } from 'next';
import '~/styles/globals.css';
import { trpc } from '~/utils/trpc';
import { Inter } from 'next/font/google';
import { NextAuthProvider } from '~/app/providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = function ({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
          {children}
        </NextAuthProvider>
      </body>
    </html>
  );
};

export default trpc.withTRPC(RootLayout);
